### PR TITLE
Create ru

### PR DESCRIPTION
**Pull request by sumhex151**

### CODE REVIEW

**Review by qtAmyVT — COMMENTED** [review]
I would like to ask the other russian translator, since there are _some_ differences between this and their own version.

**Comment by qtAmyVT** [comment]
cc. @CDh8u

**Comment by CDh8u** [comment]
I have checked mine version of the russian, and the other one. Founds out it was the same. But it didnt speaky color the text! I can already tell this is a copy of mine.

**Comment by CDh8u** [comment]
And at this point. creator doesnt know how to put a .(anything) in a file name. There was no .json at the end of the file name. I can already tell that i would like to keep my own file.

**Comment by qtAmyVT** [comment]
Probably will keep the same translations for now.

**Pull request closed without merging**
