### PR TITLE
Update ru.json

### PR DESCRIPTION
**Pull request by fily-gif**
fully translated the rest (no meqa this time :( )

### CODE REVIEW

**Comment by fily-gif** [comment]
@Meqativ can you review this so Amy can pull this pls

**Comment by meqativ** [comment]
> @Meqativ can you review this so Amy can pull this pls

it does not have to be reviewed to be pulled

**Comment by fily-gif** [comment]
> > @Meqativ can you review this so Amy can pull this pls
> 
> it does not have to be reviewed to be pulled

https://discord.com/channels/503423569192157184/1020861037165166723/1020936817308094484

**Comment by meqativ** [comment]
> > > @Meqativ can you review this so Amy can pull this pls
> > 
> > 
> > it does not have to be reviewed to be pulled
> 
> https://discord.com/channels/503423569192157184/1020861037165166723/1020936817308094484

they said to respond with an ok in the channel

**Comment by fily-gif** [comment]
> > > > @Meqativ can you review this so Amy can pull this pls
> > > 
> > > 
> > > it does not have to be reviewed to be pulled
> > 
> > 
> > https://discord.com/channels/503423569192157184/1020861037165166723/1020936817308094484
> 
> they said to respond with an ok in the channel

oh

**Pull request closed without merging**
